# See https://pre-commit.com/ for usage and config
default_language_version:
  python: python3.8
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: "v2.1.0"
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer

- repo: local
  hooks:
  - id: isort
    name: isort
    stages: [commit]
    language: system
    entry: isort
    types: [python]

  - id: black
    name: black
    stages: [commit]
    language: system
    entry: black
    types: [python]

  - id: flake8
    name: flake8
    stages: [commit]
    language: system
    entry: flake8
    types: [python]
    exclude: setup.py

  - id: mypy
    name: mypy
    stages: [commit]
    language: system
    entry: mypy
    types: [python]
    pass_filenames: false

  - id: pytest
    name: pytest
    stages: [commit]
    language: system
    entry: pytest
    types: [python]
    pass_filenames: false
    always_run: true

  - id: pytest-cov
    name: pytest
    stages: [push]
    language: system
    entry: pytest --cov
    types: [python]
    pass_filenames: false
