channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - configparser
  - flake8
  - graphviz
  - geopandas
  - isort
  - lxml
  - missingno
  - mypy
  - openpyxl
  - pandana
  - pandas-profiling >= 2.0
  - pre-commit
  - pysal
  - pytest
  - pytest-cov
  - python=3.9
  - scikit-learn
  - sphinx >= 1.7
  - sphinx-automodapi
  - sphinxcontrib-napoleon
  - sphinx_rtd_theme
  - urbanaccess  
# jupyter lab/notebook tools
  - ipykernel
  - nb_black
  - watermark
